#!/usr/bin/env bash
# Urðarbrunnr Voice Daemon — Privileged Setup Script
# Run once as: sudo bash setup.sh
# Requires: macOS, sudo, Python 3.12+
#
# What this does:
#   1. Creates OS user _openclaw-voice (system/restricted)
#   2. Creates /opt/openclaw-voice (owned by root — Zion condition 1)
#   3. Copies daemon.py to /opt/openclaw-voice/ (owned by root)
#   4. Creates /var/log/openclaw-voice + /var/run/openclaw-voice
#   5. Creates Python venv at /opt/openclaw-voice/.venv
#   6. Installs daemon dependencies into venv
#   7. Adds sudoers entry for gateway user to spawn daemon
#
# After running this, you still need to:
#   - Add the gateway token to Keychain (instructions printed at end)
#   - Add the voice-interface plugin to openclaw.json
#   - Restart the gateway

set -euo pipefail

DAEMON_USER="_openclaw-voice"
DAEMON_DIR="/opt/openclaw-voice"
LOG_DIR="/var/log/openclaw-voice"
RUN_DIR="/var/run/openclaw-voice"
GATEWAY_USER="threadweaver"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== Urðarbrunnr Voice Daemon Setup ==="
echo ""

# --- 1. OS User ---
echo "[1/7] Creating OS user ${DAEMON_USER}..."
if id "${DAEMON_USER}" &>/dev/null; then
    echo "  → User ${DAEMON_USER} already exists, skipping"
else
    sysadminctl -addUser "${DAEMON_USER}" \
        -shell /usr/bin/false \
        -home /var/empty \
        -fullName "OpenClaw Voice Daemon" \
        2>&1
    echo "  → Created ${DAEMON_USER}"
fi

# --- 2. Daemon directory (root-owned — Zion condition 1) ---
echo "[2/7] Creating ${DAEMON_DIR} (root-owned)..."
mkdir -p "${DAEMON_DIR}"
chown root:wheel "${DAEMON_DIR}"
chmod 755 "${DAEMON_DIR}"
echo "  → ${DAEMON_DIR} created, owned by root"

# --- 3. Copy daemon.py (root-owned — Zion condition 1) ---
echo "[3/7] Installing daemon.py (root-owned)..."
cp "${SCRIPT_DIR}/daemon.py" "${DAEMON_DIR}/daemon.py"
chown root:wheel "${DAEMON_DIR}/daemon.py"
chmod 644 "${DAEMON_DIR}/daemon.py"
echo "  → daemon.py installed at ${DAEMON_DIR}/daemon.py (root-owned, gateway cannot write)"

# --- 4. Log + run directories ---
echo "[4/7] Creating log and PID directories..."
mkdir -p "${LOG_DIR}" "${RUN_DIR}"
chown "${DAEMON_USER}":staff "${LOG_DIR}" "${RUN_DIR}"
chmod 750 "${LOG_DIR}" "${RUN_DIR}"
echo "  → ${LOG_DIR} and ${RUN_DIR} created, owned by ${DAEMON_USER}"

# --- 5. Python venv ---
echo "[5/7] Creating Python venv at ${DAEMON_DIR}/.venv..."
PYTHON_BIN="$(which python3)"
echo "  → Using Python: $("${PYTHON_BIN}" --version)"
"${PYTHON_BIN}" -m venv "${DAEMON_DIR}/.venv"
chown -R root:wheel "${DAEMON_DIR}/.venv"
# Allow _openclaw-voice to read/execute venv
chmod -R a+rX "${DAEMON_DIR}/.venv"
echo "  → venv created"

# --- 6. Install dependencies ---
echo "[6/7] Installing Python dependencies..."
"${DAEMON_DIR}/.venv/bin/pip" install --quiet --upgrade pip
"${DAEMON_DIR}/.venv/bin/pip" install --quiet -r "${SCRIPT_DIR}/requirements.txt"
echo "  → Dependencies installed"
echo "  → Installed packages:"
"${DAEMON_DIR}/.venv/bin/pip" list --format=columns 2>/dev/null | grep -E "fastapi|uvicorn|httpx|starlette" || true

# --- 7. Sudoers entry ---
echo "[7/7] Adding sudoers entry..."
SUDOERS_FILE="/etc/sudoers.d/openclaw-voice"
PYTHON_VENV="${DAEMON_DIR}/.venv/bin/python"
SUDOERS_LINE="${GATEWAY_USER} ALL=(${DAEMON_USER}) NOPASSWD: ${PYTHON_VENV} ${DAEMON_DIR}/daemon.py *"

cat > "${SUDOERS_FILE}" << EOF
# OpenClaw Voice Daemon — allows gateway user to spawn daemon as restricted OS user
# Generated by Urðarbrunnr setup.sh
# Reviewed and approved by Zion (2026-03-01)
${SUDOERS_LINE}
EOF
chmod 440 "${SUDOERS_FILE}"
# Validate (visudo -c will check syntax)
visudo -c -f "${SUDOERS_FILE}" && echo "  → Sudoers entry validated and installed" || {
    echo "  ✗ Sudoers syntax error! Removing file."
    rm -f "${SUDOERS_FILE}"
    exit 1
}

echo ""
echo "=== Setup complete! ==="
echo ""
echo "NEXT STEP — Add gateway token to Keychain:"
echo "  You need the OpenClaw gateway API token (from ~/.openclaw/openclaw.json → gateway.auth.token)"
echo "  Run this command:"
echo ""
echo "    security add-generic-password \\"
echo "      -a _openclaw-voice \\"
echo "      -s openclaw-voice-daemon \\"
echo "      -w '<YOUR_GATEWAY_TOKEN>'"
echo ""
echo "THEN — Test the daemon manually:"
echo "  sudo -u _openclaw-voice ${DAEMON_DIR}/.venv/bin/python ${DAEMON_DIR}/daemon.py --port 9800"
echo "  curl http://localhost:9800/health"
echo ""
echo "THEN — Add the voice-interface plugin to openclaw.json (Sethren will do this part)"
echo ""
